[build]
builder = "nixpacks"
watchPatterns = ["portal/**"]
buildCommand = "cd portal && npm install"

[deploy]
startCommand = "cd portal && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"